server:
  port: 8089

application:
  name: Votação
  versao: 0.0.1
  auth:
    jwtSecret: Zr4u7x!A%D*G-KaPdSgVkYp2s5v8y/B?E(H+MbQeThWmZq4t6w9z$C&F)J@NcRfU
    jwtExpiration: 1800000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/votacao
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
