server:
  port: 8089

application:
  name: Votação
  versao: 0.0.1

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/votacao
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
